# This is free and unencumbered software released into the public domain.

version: '3'
services:
  cassandra:
    container_name: cassandra
    image: cassandra:latest
    ports:
      - '9042:9042'
