version: '2'
services:
  playground:
    container_name: dads
    image: nmcb/dads:latest
    ports:
      - '8080:8080'
    environment:
      CLUSTER_PORT: 1600
      CLUSTER_IP: seed
      SEED_PORT_1600_TCP_ADDR: seed
