version: 2
jobs:
  test-build:
    docker:
      - image: circleci/openjdk:11-buster
        environment:
          SBT_VERSION: 1.3.10

      - image: cassandra:3.11.8
        environment:
          CASSANDRA_LISTEN_ADDRESS: 127.0.0.1

    steps:
      - checkout
      - run:
          name: Wait for Cassandra
          command: sleep 50 && nc -vz localhost 9042
      - run:
          name: Cassandra setup
          command: |
            sudo apt install -y python-pip && pip install awscli
            cqlsh -f src/main/resources/cassandra/initialise.dev.cql
            cqlsh -f src/main/resources/cassandra/dads.v1.cql
      - run:
          name: Download SBT
          command: |
            sudo apt update && sudo apt install -y wget
            sudo wget https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb -O sbt-$SBT_VERSION.deb
            sudo dpkg -i sbt-$SBT_VERSION.deb
            sudo apt update && sudo apt install sbt
      - run:
          name: Test Suite
          command: sbt test

workflows:
  version: 2
  build-and-test:
    jobs:
      - test-build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /(stage|production)-.*/
